# Unified configuration for data generation, training, and evaluation

# IMU-only generator (gen_bicycle_dual.py)
bicycle:
  out: data_cache
  seed: 42
  traj_duration_s: 500
  rate_hz: 100
  # 用作 acc/gyr 的默认窗口；若想分开，可再加 acc_window_size/gyr_window_size 覆盖
  window_size: 256
  window_stride: 128
  train_routes: 6
  val_routes: 2
  test_routes: 2
  # Kinematic bicycle physics
  wheelbase: 2.7
  rear_ratio: 0.55
  use_slip: true
  use_gravity: true
  use_roll_pitch: true
  bank_gain: 1.0
  pitch_gain: 1.0
  # Output control
  no_combined: false
  timestamp_out: false   # ✅ 关键：关闭时间戳目录，路径与 train_npz 对齐
  no_split_routes: false

# Training configuration (train.py)
train:
  route: gyr
  train_npz: data_cache/train_gyr.npz
  val_npz: data_cache/val_gyr.npz
  test_npz: data_cache/test_gyr.npz
  run_dir: runs/gyr
  epochs: 300
  batch_size: 32
  lr: 0.001
  x_mode: both
  # target_mode: pooled2  # ❌ 删除（train.py 未使用）
  logv_min: -12
  logv_max: 6
  seed: 0
  # 需要的话可加：
  # early_patience: 10
  # anchor_weight: 0.0

# Model architecture
model:
  d_model: 128
  n_tcn: 4
  kernel_size: 3
  n_heads: 4
  n_layers_tf: 2
  dropout: 0.1

runtime:
  num_workers: 0
  device: cuda

eval:
  route: gyr
  npz: data_cache/test_gyr.npz
  model: runs/gyr/best.pt
  x_mode: both

# Visual+IMU generator (gen_bicycle_dual_vis.py)
vis:
  out: data_vis          
  seed: 42
  traj_duration_s: 120
  rate_hz: 100
  train_routes: 2
  val_routes: 1
  test_routes: 1
  cam_rate_hz: 10
  img_w: 640
  img_h: 480
  fx: 400.0
  fy: 400.0
  cx: 320.0
  cy: 240.0
  vis_window: 64
  vis_stride: 32
  noise_px: 0.5
  outlier_ratio: 0.1
  min_match: 20
