# —— 一次性生成 IMU+VIS+GNSS 的多模态生成器（gen_bicycle_multi.py）
multi:
  seed: 42
  traj_duration_s: 2000
  rate_hz: 100
  train_routes: 6
  val_routes: 2
  test_routes: 2
  # 严格共轨迹的握手文件（可选）
  save_routes_meta: data_cache/routes_meta.json   # 生成时保存
  routes_meta: null                               # 复现时读取
  
  # 轨迹可视化
  plot_trajectories: true             # 生成真值轨迹图
  plot_individual: false              # 为每条轨迹生成单独的图（可选）
  plot_dir: trajectory_plots          # 轨迹图保存目录

  # 输出目录
  imu_out: data_cache
  vis_out: data_vis
  gns_out: data_gns

  # IMU（100 Hz）
  imu_window: 256
  imu_stride: 128

  # VIS（10 Hz）
  vis_window: 32
  vis_stride: 16
  noise_px: 0.35
  outlier_ratio: 0.05

  # GNSS（1 Hz）
  gns_win: 50
  gns_stride: 25
  gns_arch_enable: true
  base_sigma_en: [0.7, 0.7]
  base_sigma_u: 1.8
  scene_bounds: [400, 400, 400, 400, 400]
  scene_gain_en: [1.0, 1.5, 2.0, 1.2, 1.0]
  scene_gain_u:  [1.2, 1.8, 2.5, 1.5, 1.2]
  omega: 0.01
  alpha: 0.15
  beta: 0.75
  p_out: 0.03
  t_df: 3.0
  vendor_bias: 1.4
  vendor_ln_jitter: 0.2

# —— GNSS 训练/评测（route=gns）
train_gns:
  route: gns
  train_npz: data_gns/train_gns.npz
  val_npz:   data_gns/val_gns.npz
  test_npz:  data_gns/test_gns.npz
  run_dir:   runs/gns_tcn
  epochs: 200
  batch_size: 32
  lr: 0.001
  x_mode: both
  seed: 0
  # 建议的方差头边界与校准
  logv_min: -12
  logv_max: 5
  z2_center: 1e-3
  z2_center_target: 1.0   # GNSS 用高斯目标=1
  
  # 轴感知早停和按轴自适应加权
  early_axis: true        # 使用"最差轴 |E[z²]-1|"做早停监控
  axis_auto_balance: true # 按轴权重自适应调整
  axis_power: 1.0         # 轴权重 ~ dev^p 的指数p
  axis_clip: "0.5,2.0"    # 权重裁剪区间 [lo,hi]

model_gns:
  d_model: 128
  n_tcn: 10           # 空洞卷积感受野≈34 min（1 Hz）
  kernel_size: 3
  n_heads: 2
  n_layers_tf: 1      # 一层小注意力足够
  dropout: 0.1

eval_gns:
  route: gns
  npz: data_gns/test_gns.npz
  model: runs/gns_tcn/best.pt
  x_mode: both
